### ISSUE TITLE
[Feature Request] Amazon Prime Video support

### ISSUE THREAD

**Issue by Anderzenn** [xternal7/ultrawidify#18] opened 2018-01-26 20:22 UTC
Would be cool to have amazon prime video support!
Series such as The Grand Tour likes to add black bars for "cinematic effect" during their "action/fastpace" shots and I've been watching a couple of videos on YouTube where they do this where I really like the automatic detection for black bars. It's an awesome feature!

So if support for Amazon Prime Video was added it would be even cooler!
(Link to Amazon Prime video in case you don't know how to get to it: www.primevideo.com )

**Comment by xternal7** [comment] 2018-01-27 11:59
A couple of questions:

* Does manual detection (where you press some buttons (or the button next to the URL bar) to change aspect ratio work on Amazon Prime Video?

I'm asking because since 2.0, the manual part of the extension should attempt to work on each website that has a video on it. Of course, 'should' doesn't mean 'does,' and some sites I've tried that on are being problematic. 

I'll get around to playing around with Amazon Video at some point (seeing it's available in my country), but until then I just want to know whether the complete rewrite I've been working on was worth it. Getting the answer to these questions would also mean that I won't be going in completely blind, so I'd appreciate the answers for that reason as well. Thanks.

Second:

* Chrome or Firefox?

Amazon Video probably uses DRM, which means aspect ratio autodetection very probably isn't going to happen in Chrome due to technical reasons and limitations (detailed explanation below, if you're interested). Firefox, on the other hand, offers an alternative (although significantly more limited) way of determining the aspect ratio of a video. So here's a follow-up question:

* If you use Chrome _and_ if manual aspect ratio via keyboard shortcuts works: can you please check whether Firefox works?

Of course, **if you can't manually correct aspect ratio on Amazon, then automatic aspect ratio detection won't work either.** If you can manually correct the aspect ratio, then the script for automatic aspect ratio detection should run as well. But again, 'should' doesn't mean 'does', and sometimes it doesn't. So far, there's two exceptions that I'm aware of:

* You're watching an embedded youtube video (no aspect ratio autodetection even if you switch to full screen)

* The video is protected by a form of DRM

If it's the latter (and I believe Amazon Video does use DRM), then automatic aspect ratio is impossible-ish for technical reasons — as I've mentioned before.

Aspect ratio detection scans currently displayed frame of a video about 30-60 times per second. If the streaming platform uses DRM, aspect ratio detection script gets either a black frame (Chrome) or an error (Firefox). I like the error, it makes it easy to differentiate between dark/majorly black frames and frames that I can't get. I don't like Chrome because it's constantly telling me to go fuck myself.

On top of Firefox telling me that I can't read the current frame of a DRM-protected video (while Chrome says 'everything is fine'), it also offers a function that allows me to capture the visible content of the entire tab (basically, window capture minus the tab bar). I've tried that on Netflix and it works, with a few minor caveats:

* Player UI, while visible, can prevent automatic aspect detection from working
* It still leaves a thin black bar at the top and the bottom of the video. In theory, this thin black bar should cause reset of aspect ratio, but I haven't tested it that thoroughly

Chrome doesn't seem to provide this alternative way, though, which is why I'm not asking you to test in Chrome if you use Firefox. I know that it won't work.

Whew, this got long.

**Comment by Anderzenn** [comment] 2018-01-27 17:40
Man you didn't lie about that message being long ;)
1. Manual detection does not work on amazon prime video.
2. I use Firefox
3. I don't use chrome so I can't answer that.

I tried the keyboard shortcuts and the buttons in the menu.
I have also noticed that auto detect doesn't always work on some youtube videos, I can make a new post about that if you'd like.

**Comment by xternal7** [comment] 2018-01-27 21:29
Thanks for the answers.

Yes, please make a new post about youtube videos not working, with links to said youtube videos.

**Comment by xternal7** [comment] 2018-02-04 16:52
New version is up (v2.1.0). I haven't explicitly worked on Amazon Prime Video, but I have made some changes that made extension work on some sites that didn't work previously.

Please tell me if Amazon Video starts working with the update, any feedback much appreciated.

**Comment by Anderzenn** [comment] 2018-02-10 01:08
Hey, sorry for the kinda late reply!
It's **_kinda_** working with Prime Video now, the automatic feature will detect if a video has letter boxing and set it to the size but it won't reset back to 16:9 when the letter boxing goes away.

Good thing is that the keyboard shortcuts work now which is awesome!

**Comment by xternal7** [comment] 2018-02-10 12:31
Oh boy, I do have a problem with writing a reply that isn't miles long, don't I?

When automatic detection switches to 21:9, is there a very tiny black bar remaining on top and bottom of the video? Like 2-5 pixels wide or something? I think I know where the problem is, but not 100% certain.

Bonus round: if that's not too much work for you, please open _any_ video on Amazon video. Open browser console (F12). Make sure the video is playing. While the video is playing, this into console and hit enter:

```
console.log("this many videos: ", document.getElementsByTagName("video").length);
```
Console should say `this many videos: 1`. If that number is different than 1, please mention it.
```
var vid = document.getElementsByTagName("video")[0];
var canvas = document.createElement("canvas");
canvas.style.position = "absolute";
canvas.style.left = "200px";
canvas.style.top = "200px";
canvas.style.zIndex = 10000;
canvas.width = 1280;
canvas.height = 720;
canvas.id = "uw_ArDetect_canvas";
var context = canvas.getContext("2d");
var test = document.getElementsByTagName("body")[0];
test.appendChild(canvas);
```
This should get you a black rectangle that covers the video and just about everything. It should be 1280x720 pixels big, 200 pixels from the top, 200 pixels from the left. In some cases, the rectangle could be covered by the video. If that's the case, the console should reply with:
```
<canvas style="position: absolute; left: 200px; top: 200px; z-index: 10000;" width="1280" height="720" id="uw_ArDetect_canvas"> ¤
```
If you hover over the square at the end of the line, firefox should highlight this rectangle. If you get that far, you're doing it right.

Now, paste this into the console and press 'enter':
```
context.drawImage(vid, 0,0, 1280, 720);
```

When you do this, one of two things will happen. Either the response will be this - or something along those lines:
```
[Exception... "Component is not available"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: debugger eval code :: <TOP_LEVEL> :: line 1"  data: no]
```
and I'll have a vague idea of where things are going wrong.  This response means the video is DRM protected, which means I have to resort to some workarounds to get it working — and said workarounds don't give me ton of space. (This is also the reason autodetection _should_ leave 2-5px tall black border at the top and bottom of the video when it does its correction). 

Or it's gonna be this:

```
undefined
```

In which case the things have become a little more complicated (if you get this response, you absolutely shouldn't be experiencing that).

**Comment by xternal7** [comment] 2018-03-13 23:49
So I've changed a few things on the extension. The next update is going to disable extension on all sites other than Youtube and Netflix by default (as it was kinda breaking reddit and imgur). However, you can still enable extension on any site via quick settings (see screencap). 

After a reload, the extension should work the same way as it did before (except it shouldn't make Youtube lag as much). 

![screenshot_20180314_004614](https://user-images.githubusercontent.com/12505802/37375687-1a95e29a-2721-11e8-9b49-f85f6f3acbdd.png)

**Comment by xternal7** [comment] 2019-06-02 23:14
As of v4.0.0, extension should work on all sites (unless they're special little snowflake like vimeo). Since I've got no way of testing on amazon prime, I'll just close this and hope it works, and deal with a new issue if it doesn't.

**Closed by xternal7** 2019-06-02 23:14 UTC
Labels: feature request
