### ISSUE TITLE
is not working on netflix

### ISSUE THREAD

**Issue by corincorvus** [xternal7/ultrawidify#8] opened 2017-10-16 19:35 UTC
Hey,

i want to watch films in 21:9 with max zoom for my display. but it dont work. hotkeys dont work and after restart the browser it dont solve the problem.

Firefox Quantum
Addon Version 1.2.1.1

**Comment by xternal7** [comment] 2017-10-17 19:55
Thanks for making me aware. Unfortunately, this isn't going to be fixed in a while (personal issues) as far as the regular version is concerned.

If you're feeling a bit adventurous, you could try [this temporary alpha version](http://tamius.net/ultrawidify/versions-git/ultrawidify_git-2.0a1.xpi).

Things you should know:

* No automatic updates for this version (I'll notify you when the changes make it to the regular, stable version)
* You should disable the extension you installed from AMO until the issue is fixed
* Only works in fullscreen (except on Vimeo, where I toyed with its player a little)
* You can't turn off auto aspect ratio detection (unless you use keyboard shortcuts)
* **UI is gone.**

If you go and use this version until I manage to get access to netflix, please come back and report:
* Does this version work on netflix?
* Your hardware (CPU, bonus: RAM, GPU)
* How's CPU usage?
* If you're using anything other than netflix and youtube, does this version work on those sites as well
* Is this extension broken anywhere?
* Does this extension break any page you visit (as it runs everywhere by default)

**Closed** 2018-01-01 11:20 UTC
