### ISSUE TITLE
Shifted Screen

### ISSUE THREAD

**Issue by lahmah** [xternal7/ultrawidify#15] opened 2018-01-11 02:03 UTC
When I watch any 21:9 or 18:9 movie on Netflix the screen is shifted upwards so that a black bar remains at the bottom and a part of the picture is missing at the top.

**Comment by xternal7** [comment] 2018-01-11 08:36
Can I have your browser/OS and other extensions you're using? I can't reproduce, but this is the second time this week I'm seeing someone mention that problem.

**Comment by lahmah** [comment] 2018-01-11 12:33
I'm using firefox 57.0.4 on arch linux and windows 10.
I just tested on both OS a new firefox profile without any configuration and addons except ultrawidify and still had the problem.

**Comment by xternal7** [comment] 2018-01-11 16:33
But _not_ on youtube?

🤔 🤔 🤔 

I did manage to reproduce it though (I'm still holding on FF56 on Linux, but I have the new one on Windows). It seems this is an issue only with FF57 for some reason, and oh boy does it completely wreck autodetection on Netflix as well.

**Comment by xternal7** [comment] 2018-01-11 16:40
Note to self (when I come home):

Resizer.js, _res_applyCss() -- the problem is probably here, `top: -something px` probably conflicts with that object fit line (if it wasn't removed), which was needed for vid.me when it was still a thing.

**Comment by xternal7** [comment] 2018-01-12 22:27
The issue seems to have been resolved and update has been pushed to AMO. I'll be closing the issue now, but if the update doesn't fix the problem for you feel free to reopen this issue. 

In any case, thanks for reporting the problem. It's much appreciated.


**Technical details** (if anyone cares)

The problem was with setting CSS. For some reason, `<video>` tag had `position: relative` set on it. It shouldn't be, because I'm overriding that with `position: absolute !important`, which should override any CSS defined by Netflix. So there's nothing wrong with the extension, the problem is somewhere else, and that makes it a bit more annoying to fix.

Because `position` was set to `relative` and not `absolute`, the `margin: auto` tried to vertically center the `<video>` tag - and that conflicted with how I'm centering video vertically. (`position: absolute !important` and negative offset for `top` property, mostly due to legacy reasons). 

Solution: have the extension inject `margin: 0px !important` into `<video>`'s css. It seems to work.

**Closed by xternal7** 2018-01-12 22:27 UTC
Labels: Firefox, bug
