### ISSUE TITLE
Doesn't work on Chrome any more.

### ISSUE THREAD

**Issue by Arkadius1984** [xternal7/ultrawidify#35] opened 2018-03-19 21:06 UTC
Dear Creator, your app was great. I was so happy to finally watch a movies on Netflix and Google Play in a proper Aspect ratio on my Ultra-wide Monitor. This app was working perfectly. Now it doesn't work at all. I tried to uninstall and reinstall it and still not working.  There is only a message: "No videos were detected on this page. The buttons may not work at all. Check that this site is not blacklisted and reload the page." Please make that working again :(

**Comment by jimicze** [comment] 2018-09-01 11:02
Same, doesnt work in chrome. THe problem can be in shortcuts ..

**Comment by xternal7** [comment] 2018-09-01 12:17
That's strange, because Chrome seems to work for me just fine (and this issue was fixed ages ago. I guess I forgot to close it). The only thing that doesn't seem to work on Chrome at the moment is shortcut for automatic detection. Other shortcuts and things seem to work.


Are there any extra steps to reproduce this problem?

**Closed** 2018-09-23 01:02 UTC
Labels: No info provided
