### ISSUE TITLE
Incompatibility with Iridium: Video flickers between left side and center

### ISSUE THREAD

**Issue by Berny23** [xternal7/ultrawidify#67] opened 2019-06-25 15:05 UTC
I'm using the latest version on firefox (from addons.mozilla.org) together with Iridium for YouTube.
I've had the problem for a few months now. I didn't have it with older versions.

I uploaded a short example screen capture here: https://streamable.com/c9w4b

When I disable Ultrawidify and reload the youtube page the issue is gone.

**Comment by xternal7** [comment] 2019-06-25 23:30
>I've had the problem for a few months now.

Can you be a bit more specific? If it's started happening before the start of this month, the issue definitely exists in old versions as well (2019-06-03 was when 4.x happened. Last update before that was september or october 2018). 

Preliminary results put the blame on Iridium messing with the page, as the issue only happens when Iridium is on. Interestingly enough, this flicker only seems to happen while pausing/unpausing.

**Comment by xternal7** [comment] 2019-06-25 23:41
I've looked into Iridium settings a bit more. Settings are fun. 'Memorize player size' option sounds like the likely culprit because could be touching the same thing that I need to touch in order to ensure the video fits the player.

I cannot verify right now because my laptop's wireless card just shits itself every time I try to load any page that contains anything other than text, though.

**Comment by Berny23** [comment] 2019-06-26 13:27
Thanks for investigating this! But sadly I didn't keep track of which versions I was using back then. And "months" was just a guess. 
It could also be a problem with a newer version of Iridium.

**Comment by xternal7** [comment] 2019-06-27 09:02
>But sadly I didn't keep track of which versions I was using back then. And "months" was just a guess.

Well, firefox _does_ allow you to downgrade to earlier versions if you really wanna test. Though now that I've roughly figured what causes the issue, that isn't really necessary. 99% you'll get the same issue with anything from the 3.x version (not to mention downgrading would probably cause more issues than it would solve).

Did disabling 'memorize player size' help the problem?

Option 2: go to 'video and player detection' tab in the popup, uncheck _Detect automatically_ under **Player detection settings**, paste `#movie_player` in 'query selectors' box:

![Screenshot_20190627_105702](https://user-images.githubusercontent.com/12505802/60252309-4f22b080-98ca-11e9-99f4-2338bc5d8f46.png)

I haven't had the chance to investigate how iridium changes stuff yet.

**Comment by Berny23** [comment] 2019-06-27 13:14
I tried the two options in a fresh portable firefox but it it didn't work: https://streamable.com/for5j
It gets even worse by using the small iridium player in the lower right corner.

**Comment by xternal7** [comment] 2019-06-27 13:47
What happens after page reload (`ctrl+f5`) or in a new tab?

2\. TheFatRat video the other day was 16:9 no black bars, this one is 16:9 but with black bars. 

Here's what seems to be going on in this example: ultrawidify notices detects black edges and crops the video accordingly. Iridium sees that size of the video has changed and throws a shit fit, undoing changes. Ultrawidify notices that someone reverted its changes (because youtube often does that) and re-applies its settings because obviously ultrawidify knows best. Iridium notices the change and undoes it again. And ultrawidify re-applies it again because jesus fuck this is 21:9 video with a black bar, god dammit. And Iridium undoes it, again. Repeat forever.

* [This video should have tons of flicker (16:9 with blackbars)](https://www.youtube.com/watch?v=jPEYpryMp2s)
* [This video should have less flicker (16:9 without blackbars)](https://www.youtube.com/watch?v=GUsu1R3bOvY)

**Comment by Berny23** [comment] 2019-06-27 20:22
The second video works fine without flickering, even if I scroll down and up again. But as soon as I press "E" or "D", it flickers again. Strangely enough, the automatic mode (key "A") removes the flickering. But by pressing "A" the image is moved permanently to the left until I scroll down and up again. I had "memorize player size" off during this time.

Example (without key -> key "E" -> key "A"): https://streamable.com/v8ynz

**Comment by xternal7** [comment] 2019-07-03 18:40
Status update (actually more like notes to self):

* Video permanently aligned to right: something strips away `transform()` and `scale()` from the style string. For some reason, the checher of css spaghetti doesn't detect when someone touched that spaghett. 

* Blank mini square: transform and scale should be recalculated under these circumstances, but aren't for some reason. (Happens always after aspect ratio has been changed or reset, but not until extension found a reason to correct video)

* Flicker issue: not my problem. On play/pause, something strips away my CSS, but CSS _is_ re-applied correctly in this case.

This is getting more fun than I bargained for.

**Comment by xternal7** [comment] 2019-07-04 21:09
Good news. Fixed all the issues that were actually issues on my end — that is, black mini square and video being permanently aligned to the left.

As stated before, flicker isn't really my issue. It's caused by what seems to be Iridium overriding my styles (fortunately for us, it backs off quickly).

------------

Technical details about the bugs:

### Blank mini square

This issue _is_ fixed by query selector, it's just that the config on my dev machine lacked it for some reason.

### Video permanently aligned to the right 

When an aspect ratio is set, the extension saves the aspect ratio (e.g. 1.77) as well as its type (automatic, manual, etc).

If player changes size (or if youtube or something else changes styles on <video> element), extension will re-apply the saved aspect ratio. 

Default aspect ratio when using autodetection was 'null' instead of a number. Because of that, the extension couldn't determine how to crop the video and where to align it, and because of that the video ended up aligned to the left side. 

-----

New version will be released this weekend, probably — I have to figure how to selectively override user settings so I can override bad "defaults."

**Closed by xternal7** 2019-07-04 21:09 UTC
Labels: conflicts with other addon
