### ISSUE TITLE
Version 4.0 no longer works with Netflix

### ISSUE THREAD

**Issue by HiCKSsan** [xternal7/ultrawidify#66] opened 2019-06-04 18:25 UTC
**Describe the bug**
Hello, thanks you for your work, I just want to tell you since version 4.0 UltraWidify no longer works with Netflix, I went back to the previous version and everything works well.

**To Reproduce**
Version 4.0

**Browser and OS**
 * Browser/browser version: Firefox 67.0 (64 bits)
 * Operating system: WIn 10
 * Ultrawidify version: 4.0

**Additional info**
Thanks you :)

**Comment by Fabi0Z** [comment] 2019-06-05 10:31
Same problem with Prime Video, I've also tried to reset the extension settings but nothing has changed

**Browser and OS**

- Browser/browser version: Firefox Developer Edition 68.0b7 (64 bits)
- Operating system: macOS Mojave 10.14.5 / Windows 10
- Ultrawidify version: 4.0

**Comment by xternal7** [comment] 2019-06-05 13:43
@HiCKSsan Just autodetection or did keyboard shortcuts (and popup) stop working as well?

In any case, when watching on netflix, go to 'site settings' section of the popup and click 'enable' for both (assuming you haven't already). Does that fix the issue?

@Fabi0Z Do same thing, except on Amazon prime.

I've spotted a similar issue on streamable, where `Extension settings` tab in the popup has extension mode/autodetection mode set to `Enabled`, but `Site settings` has those two options set to `default`. 

In theory, extension should work because `default` on site settings should mean `enabled`, but on Streamable for some reason doesn't.

**Comment by Fabi0Z** [comment] 2019-06-05 15:47
@xternal7 changing site settings to "Enable" has solved the problem

**Comment by xternal7** [comment] 2019-06-05 22:24
As I suspected. I've also found the problem but for reals. The update that fixes this behaviour should land soon (in the next few days at latest), depending on how fast Firefox and Chrome will download the update.

The Netflix issue was something else, though, but I've managed to reproduce it. It seems to be fixed now.

Thanks for reporting the issue, mates. Much appreciated.

**Closed by xternal7** 2019-06-05 22:24 UTC
