### ISSUE TITLE
memory usage grow up to 100 percent

### ISSUE THREAD

**Issue by DeoHeo** [xternal7/ultrawidify#32] opened 2018-03-07 23:48 UTC
OS: Windows 8.1 (64-Bit)
Browser: Firefox 58.0.2 (64-Bit)
Addon: Ultrawidify 2.1.4
Website: youtube.com
Issuses Description: I saw same movie on youtube, than grow up the memory usage to approximately 100 percent. Its fluctuate little. When I disable the addon than is the memory usage normal. The file "memory-report.json.gz" have a report about the memory usage from the browser. You can look for the pid 2788.

If you need any further information, I can give it to you.
Please excuse my bad English.
![2018-03-08 00_22_55-task manager](https://user-images.githubusercontent.com/36903053/37124856-64c4ccde-226a-11e8-98d5-7df61fd47df0.png)
[memory-report.json.gz](https://github.com/xternal7/ultrawidify/files/1791315/memory-report.json.gz)

**Comment by xternal7** [comment] 2018-03-08 21:11
First of all, let me commend you for including all that info in the report. 

Good news: this looks like a possible duplicate of #25, which is being worked on. Estimated RAM usage will go from 'too much' to 'between 50-400 MB per video played' when I release the fix.

By the way — how much RAM do you have in your PC?

**Comment by DeoHeo** [comment] 2018-03-09 14:19
Thank you for the fast answer and for fix the problem. I like your Addon, good work. 

I follow the issues #25. 

I have 6 GB.

**Closed** 2018-03-13 23:11 UTC
Labels: Chrome, Firefox, bug, duplicate

**Comment by xternal7** [comment] 2018-03-13 23:16
So here's what was done: 

* Improvements that were being implemented to autodetection increased RAM usage by _a lot_. Up to 400 MB if firefox was freshly started, up to (and sometimes over) 2 GB in case of Firefox running for a while or if the number of tabs was higher
* As a result, the resolution of the sample image was reduced
* Default rate at which I check for changes was also reduced from 30 per second to 1 per second, which reduces the amount of RAM used to the point where RAM usage is negligible.

This should fix issues with RAM at cost of automatic detection not instantly reacting to changes.
