### ISSUE TITLE
BAG

### ISSUE THREAD

**Issue by batyazek** [xternal7/ultrawidify#23] opened 2018-02-21 12:58 UTC
21:9 doesnt work, AUTO-detect dont work too.when i use hot-key (D) video comes ultra-wide,but а fer seconds after video comes to it first resolution. it s terrible , please fix it

**Comment by xternal7** [comment] 2018-02-21 13:51
1. Which browser?
2. Which website?
3. Which video (links?)

**Comment by xternal7** [comment] 2018-02-22 21:15
Assuming this is duplicate of #24, this issue should be fixed.

**Closed by xternal7** 2018-02-22 21:15 UTC
Labels: needs-info
